# Generated by Django 4.2.6 on 2025-05-07 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('idNovedad', models.AutoField(primary_key=True, serialize=False)),
                ('oficina', models.CharField(choices=[('1', 'AGUASCALIENTES'), ('2', 'BAJA CALIFORNIA'), ('3', 'BAJA CALIFORNIA SUR'), ('4', 'CAMPECHE'), ('5', 'COAHUILA'), ('6', 'COLIMA'), ('7', 'CHIAPAS'), ('8', 'CHIHUAHUA'), ('9', 'CDMX'), ('10', 'DURANGO'), ('11', 'GUANAJUATO'), ('12', 'GUERRERO'), ('13', 'HIDALGO'), ('14', 'JALISCO'), ('15', 'EDOMEX'), ('16', 'MICHOACÁN'), ('17', 'MORELOS'), ('18', 'NAYARIT'), ('19', 'NUEVO LEÓN'), ('20', 'OAXACA'), ('21', 'PUEBLA'), ('22', 'QUERÉTARO'), ('23', 'QUINTANA ROO'), ('24', 'SAN LUIS POTOSÍ'), ('25', 'SINALOA'), ('26', 'SONORA'), ('27', 'TABASCO'), ('28', 'TAMAULIPAS'), ('29', 'TLAXCALA'), ('30', 'VERACRUZ'), ('31', 'YUCATÁN'), ('32', 'ZACATECAS')], default='9', max_length=2)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('no_migrantes', models.IntegerField(default=0)),
                ('nacionalidades', models.CharField(max_length=300)),
                ('archivoN', models.FileField(blank=True, null=True, upload_to='novedad/')),
                ('autoridades', models.ManyToManyField(blank=True, to='novedad.autoridad')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novedad.evento')),
            ],
        ),
    ]
