# Generated by Django 4.2.6 on 2025-05-09 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novedad', '0002_novedades_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedades',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
